---
- name: ldconfig
  command: "/usr/sbin/ldconfig"
  become: true

- name: Gather local facts
  setup:
    gather_subset: local

- name: Reconfigure interfaces
  include: tasks/find_live_ifaces.yml

- name: Build SNF
  include: handlers/build_snf_driver.yml
