---
- name: Set the hash key to the right multiple
  set_fact:
    _intel_hkey_mult: "{{ intel_hash_key_length/(intel_hash_key_pattern | length) }}"

- name: Extend the hash key to the full length
  set_fact:
    _intel_hkey_list: "{{ intel_hash_key_pattern * (_intel_hkey_mult|int) }}"

- name: Build the final hash key
  set_fact:
    _intel_hkey: "{{ _intel_hkey_list | join(':') | lower }}"

- name: Copy irq_affinity script
  copy:
    src: set_irq_affinity
    dest: /usr/local/sbin/
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Create device configuration unit
  template:
    src: "intel_systemd.j2"
    dest: "/etc/systemd/system/tuning_{{ capture_iface.iface }}.service"
    mode: '0644'
    owner: root
    group: root
  become: true

