---
- name: Install dependencies
  package:
    name:
      - python3
      - pciutils
    state: present
  become: true


- name: Create fact directory
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    owner: root
    group: root
  loop:
    - /etc/ansible
    - /etc/ansible/facts.d
  become: true

- name: Create NIC fact
  template:
    src: nics.fact.j2
    dest: /etc/ansible/facts.d/nics.fact
    mode: "0775"
    owner: root
    group: root
  become: true
  notify: Gather local facts

- name: Force handlers to run, to regather NIC facts
  meta: flush_handlers

- name: Detect our interfaces
  include: find_live_ifaces.yml

- name: Configure any Intel NICs
  include: config_intel.yml
  when: (capture_ifaces | length) and capture_iface.manufacturer == "Intel"

- name: Configure any Myricom NICs
  include: config_myricom.yml
  # The logic here is weird, because we can't detect which ports are up/down before we install the SNF driver
  when: (ansible_local.nics | length) and ansible_local.nics[0].manufacturer == "Myricom"

- name: Enable our service
  systemd:
    name: "tuning_{{ capture_iface.iface }}.service"
    enabled: yes
    daemon_reload: yes
    state: started
  when: capture_ifaces | length
  become: true
