---
- name: Create fact directory
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    owner: root
    group: root
  loop:
    - /etc/ansible
    - /etc/ansible/facts.d
  become: true

- name: Create NIC fact
  template:
    src: nics.fact.j2
    dest: /etc/ansible/facts.d/nics.fact
    mode: "0775"
    owner: root
    group: root
  become: true
  register: nic_fact

- debug:
    var: ansible_version

- name: Gather NIC facts when our fact updates
  setup:
    gather_subset: local
  when: nic_fact.changed

- name: Determine which interface is up
  set_fact:
    capture_ifaces: "{{ ansible_local.nics | selectattr('carrier', 'defined') | selectattr('carrier', 'true') | selectattr('port', 'defined') | selectattr('port', 'equalto', 'FIBRE') | list }}"

- name: Print out NIC configuration
  debug:
    var: capture_ifaces
